# Generated by Django 4.2.7 on 2023-12-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='name',
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Passive', 'Passive'), ('Portfolio', 'Portfolio')], default='Salary', max_length=255),
        ),
    ]
